services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "4321:4321"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./astro.config.mjs:/app/astro.config.mjs

  prod:
    build:
      context: .
      target: prod
    ports:
      - "8080:80"
